name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.GIT_TOKEN }}

      - name: Use Secret Key
        run: echo "The secret key is ${{ secrets.API_KEY }}"
        
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # - name: Install dependencies
      #   run: npm install

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g nx


      # Step 4: Build the application (if applicable)
      - name: Build application
        run: |
          npx nx run property:build
          #npx nx run checkout:build
          # npx nx run dashboard:build
        env:
          NODE_ENV: production
          REACT_APP_API_KEY: ${{ secrets.GIT_TOKEN }}

      - name: Use GitHub Secret Token
        env:
          GITHUB_SECRET: ${{ secrets.GIT_TOKEN }}
        run: echo "Using GitHub Secret Token for tasks"

      # - name: Verify index.html Content
      #   run: cat dist/apps/checkout/index.html


      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          deployment_action: "upload"   
          app_location: "dist/apps/property"            # Adjust if your app is in a subfolder
           # output_location: "build"     # Adjust if your build folder has a different name
          output_location: "dist/apps/checkout" # Build output folder
