name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # - name: Install dependencies
      #   run: npm install

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g nx


      # Step 4: Build the application (if applicable)
      - name: Build application
        run: |
          npx nx run property:build
          npx nx run checkout:build
          npx nx run dashboard:build
        env:
          NODE_ENV: production
